package com.example.archshowcase.replayable.processor

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.symbol.KSClassDeclaration
import java.io.OutputStream

/**
 * 为 @ReplayableStore 注解生成 ExportStrategy 实现（jvmMain）
 */
class ExportStrategyGenerator(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger
) {
    fun generate(
        packageName: String,
        storeName: String,
        storeFullName: String,
        stateFullName: String,
        recordFullName: String,
        storeNameConstant: String,
        classDeclaration: KSClassDeclaration
    ) {
        val strategyName = "${storeName}ExportStrategy"

        // 生成到同一个包（commonMain），不跨包！
        val file = codeGenerator.createNewFile(
            Dependencies(true, classDeclaration.containingFile!!),
            packageName,  // 生成到 Store 同包
            strategyName
        )

        file.use { out ->
            out.appendText("// Auto-generated by Replayable KSP Processor\n")
            out.appendText("@file:Suppress(\"unused\")\n\n")
            out.appendText("package $packageName\n\n")

            // 导入必要的类
            out.appendText("import com.example.archshowcase.core.trace.export.SimpleExportStrategy\n")
            out.appendText("import com.example.archshowcase.core.trace.restore.RestorableState\n\n")

            // 生成 ExportStrategy 对象
            out.appendText("""
                |/**
                | * Export strategy for $storeName
                | *
                | * Auto-generated based on @ReplayableStore annotation.
                | * Generated to commonMain (not jvmMain) for future iOS support.
                | */
                |internal object $strategyName : SimpleExportStrategy<$stateFullName, $recordFullName>(
                |    storeName = $storeNameConstant,
                |    getHistory = { it.history },
                |    getTimestamp = { it.timestamp },
                |    recordKSerializer = $recordFullName.serializer()
                |) {
                |    override fun createInitialState(): RestorableState = $stateFullName()
                |
                |    override fun processRecord(
                |        record: $recordFullName,
                |        prevState: $stateFullName
                |    ): Triple<$stateFullName, Any, Any?> {
                |        val currentState = record.applyToState(prevState)
                |        val intent = record.toIntent()
                |        return Triple(currentState, intent, null)
                |    }
                |}
                |
            """.trimMargin())
        }
    }

    private fun OutputStream.appendText(str: String) {
        this.write(str.toByteArray())
    }
}
