package com.example.archshowcase.replayable.processor

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.symbol.KSFile
import java.io.OutputStream

/** Intent 子类模型 */
sealed interface IntentEntry {
    val simpleName: String

    /** data object — 无参数 Intent */
    data class ObjectIntent(override val simpleName: String) : IntentEntry

    /** data class — 带参数 Intent */
    data class DataClassIntent(
        override val simpleName: String,
        val params: List<IntentParamInfo>
    ) : IntentEntry
}

/** Intent 参数解析信息 */
data class IntentParamInfo(
    val name: String,
    val typeName: String,
    val parseExpression: String,
    val imports: List<String> = emptyList()
)

class IntentResolverGenerator(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger
) {

    fun generateResolver(
        packageName: String,
        storeSimpleName: String,
        storeQualifiedName: String,
        functionName: String,
        intentEntries: List<IntentEntry>,
        originatingFile: KSFile
    ) {
        val fileName = "${storeSimpleName}IntentResolver"

        val file = codeGenerator.createNewFile(
            Dependencies(true, originatingFile),
            packageName,
            fileName
        )

        file.use { out ->
            out.appendText("// Auto-generated by VfResolvable KSP Processor\n")
            out.appendText("// DO NOT EDIT - This file is regenerated on every build\n")
            out.appendText("@file:Suppress(\"unused\")\n\n")
            out.appendText("package $packageName\n\n")

            // 收集并输出 imports
            val imports = mutableSetOf<String>()
            imports.add("com.example.archshowcase.core.trace.verification.VfIntent")
            intentEntries.filterIsInstance<IntentEntry.DataClassIntent>().forEach { entry ->
                entry.params.forEach { param -> imports.addAll(param.imports) }
            }
            imports.sorted().forEach { out.appendText("import $it\n") }
            out.appendText("\n")

            // 生成解析函数
            out.appendText("internal fun $functionName(\n")
            out.appendText("    vfIntent: VfIntent\n")
            out.appendText("): $storeSimpleName.Intent? = when (vfIntent.intentType) {\n")

            for (entry in intentEntries) {
                when (entry) {
                    is IntentEntry.ObjectIntent -> {
                        out.appendText("    \"${entry.simpleName}\" -> $storeSimpleName.Intent.${entry.simpleName}\n")
                    }
                    is IntentEntry.DataClassIntent -> {
                        if (entry.params.size == 1) {
                            // 单参数：单行
                            val param = entry.params[0]
                            out.appendText("    \"${entry.simpleName}\" -> $storeSimpleName.Intent.${entry.simpleName}(\n")
                            out.appendText("        ${param.name} = ${param.parseExpression}\n")
                            out.appendText("    )\n")
                        } else {
                            // 多参数
                            out.appendText("    \"${entry.simpleName}\" -> $storeSimpleName.Intent.${entry.simpleName}(\n")
                            entry.params.forEachIndexed { index, param ->
                                val comma = if (index < entry.params.size - 1) "," else ""
                                out.appendText("        ${param.name} = ${param.parseExpression}$comma\n")
                            }
                            out.appendText("    )\n")
                        }
                    }
                }
            }

            out.appendText("    else -> null\n")
            out.appendText("}\n")
        }

        logger.info("Generated $fileName with ${intentEntries.size} intent entries")
    }

    private fun OutputStream.appendText(str: String) {
        write(str.toByteArray())
    }
}
