package com.example.archshowcase.replayable.processor

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.symbol.KSFile
import java.io.OutputStream

class RouteSerializationGenerator(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger
) {
    fun generate(
        packageName: String,
        sealedName: String,
        sealedQualifiedName: String,
        entries: List<RouteEntry>,
        fallback: String,
        originatingFile: KSFile
    ) {
        val fileName = "${sealedName}Serialization"
        val file = codeGenerator.createNewFile(
            Dependencies(true, originatingFile),
            packageName,
            fileName
        )

        val objectEntries = entries.filterIsInstance<RouteEntry.ObjectRoute>()
        val paramEntries = entries.filterIsInstance<RouteEntry.ParameterizedRoute>()

        file.use { out ->
            out.appendText("// Auto-generated by RouteRegistry KSP Processor\n")
            out.appendText("// DO NOT EDIT - This file is regenerated on every build\n")
            out.appendText("@file:Suppress(\"unused\")\n\n")
            out.appendText("package $packageName\n\n")

            generateObjectRoutesMap(out, sealedName, objectEntries)
            generateSerialName(out, sealedName, objectEntries, paramEntries)
            generateFromSerialName(out, sealedName, paramEntries, fallback)
        }

        logger.info("Generated $fileName with ${entries.size} routes")
    }

    private fun generateObjectRoutesMap(
        out: OutputStream,
        sealedName: String,
        objectEntries: List<RouteEntry.ObjectRoute>
    ) {
        out.appendText("private val objectRoutes: Map<String, $sealedName> = mapOf(\n")
        objectEntries.forEachIndexed { index, entry ->
            val comma = if (index < objectEntries.size - 1) "," else ""
            out.appendText("    \"${entry.simpleName}\" to $sealedName.${entry.simpleName}$comma\n")
        }
        out.appendText(")\n\n")
    }

    private fun generateSerialName(
        out: OutputStream,
        sealedName: String,
        objectEntries: List<RouteEntry.ObjectRoute>,
        paramEntries: List<RouteEntry.ParameterizedRoute>
    ) {
        out.appendText("val $sealedName.serialName: String get() = when (this) {\n")
        objectEntries.forEach { entry ->
            out.appendText("    $sealedName.${entry.simpleName} -> \"${entry.simpleName}\"\n")
        }
        paramEntries.forEach { entry ->
            val paramExpr = entry.params.joinToString(",") { "\$$it" }
            out.appendText("    is $sealedName.${entry.simpleName} -> \"${entry.simpleName}($paramExpr)\"\n")
        }
        out.appendText("}\n\n")
    }

    private fun generateFromSerialName(
        out: OutputStream,
        sealedName: String,
        paramEntries: List<RouteEntry.ParameterizedRoute>,
        fallback: String
    ) {
        out.appendText("fun $sealedName.Companion.fromSerialName(name: String): $sealedName {\n")
        out.appendText("    objectRoutes[name]?.let { return it }\n")

        paramEntries.forEach { entry ->
            val prefix = "${entry.simpleName}("
            out.appendText("    if (name.startsWith(\"$prefix\") && name.endsWith(\")\")) {\n")

            if (entry.params.size == 1) {
                out.appendText("        val ${entry.params[0]} = name.removePrefix(\"$prefix\").removeSuffix(\")\")\n")
            } else {
                out.appendText("        val parts = name.removePrefix(\"$prefix\").removeSuffix(\")\").split(\",\")\n")
                entry.params.forEachIndexed { i, param ->
                    out.appendText("        val $param = parts[$i]\n")
                }
            }

            val args = entry.params.joinToString(", ") { "$it = $it" }
            out.appendText("        return $sealedName.${entry.simpleName}($args)\n")
            out.appendText("    }\n")
        }

        out.appendText("    return $sealedName.$fallback\n")
        out.appendText("}\n")
    }

    private fun OutputStream.appendText(str: String) {
        this.write(str.toByteArray())
    }
}
