package com.example.archshowcase.replayable.processor

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSType
import com.google.devtools.ksp.symbol.Variance
import java.io.OutputStream

/**
 * 为 @SelectableState 生成 StateFields holder 类和 rememberFields() 扩展函数
 */
class SelectableStateFieldsGenerator(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger
) {

    companion object {
        /** 装箱后 === 不可靠的原始类型，必须用 equals */
        private val EQUALS_ONLY_TYPES = setOf(
            "kotlin.Int",
            "kotlin.Long",
            "kotlin.Short",
            "kotlin.Byte",
            "kotlin.Float",
            "kotlin.Double",
            "kotlin.Char",
        )
    }

    fun generate(
        packageName: String,
        storeName: String,
        fields: List<StateFieldInfo>,
        classDeclaration: KSClassDeclaration
    ) {
        val className = "${storeName}StateFields"
        val imports = mutableSetOf<String>()

        val resolvedFields = fields.map { field ->
            val (typeStr, fieldImports) = resolveType(field.type, packageName)
            imports.addAll(fieldImports)
            Triple(field.name, typeStr, useRefEquality(field.type))
        }

        val file = codeGenerator.createNewFile(
            Dependencies(true, classDeclaration.containingFile!!),
            packageName,
            className
        )

        file.use { out ->
            out.appendText("// Auto-generated by SelectableState KSP Processor\n")
            out.appendText("// DO NOT EDIT - This file is regenerated on every build\n")
            out.appendText("@file:Suppress(\"unused\")\n\n")
            out.appendText("package $packageName\n\n")

            // 固定 import
            val hasRefFields = resolvedFields.any { it.third }
            out.appendText("import androidx.compose.runtime.Composable\n")
            out.appendText("import androidx.compose.runtime.State\n")
            out.appendText("import androidx.compose.runtime.getValue\n")
            out.appendText("import com.example.archshowcase.core.compose.selectAsState\n")
            if (hasRefFields) {
                out.appendText("import com.example.archshowcase.core.compose.selectRefAsState\n")
            }
            out.appendText("import kotlinx.coroutines.flow.StateFlow\n")

            // 动态 import（排序保证确定性输出）
            for (imp in imports.sorted()) {
                out.appendText("import $imp\n")
            }

            out.appendText("\n")

            // Fields holder 类
            out.appendText("class $className(\n")
            for ((name, typeStr, _) in resolvedFields) {
                out.appendText("    $name: State<$typeStr>,\n")
            }
            out.appendText(") {\n")
            for ((name, typeStr, _) in resolvedFields) {
                out.appendText("    val $name: $typeStr by $name\n")
            }
            out.appendText("}\n\n")

            // rememberFields() 扩展函数
            out.appendText("@Composable\n")
            out.appendText("fun StateFlow<$storeName.State>.rememberFields(): $className =\n")
            out.appendText("    $className(\n")
            for ((name, _, useRef) in resolvedFields) {
                val fn = if (useRef) "selectRefAsState" else "selectAsState"
                out.appendText("        $fn { $name },\n")
            }
            out.appendText("    )\n")
        }

        logger.info("Generated $className with ${resolvedFields.size} fields")
    }

    /** 装箱原始类型用 equals，其余类型用引用比较（===） */
    private fun useRefEquality(type: KSType): Boolean {
        val qn = type.declaration.qualifiedName?.asString() ?: return false
        return qn !in EQUALS_ONLY_TYPES
    }

    private fun resolveType(type: KSType, currentPackage: String): Pair<String, Set<String>> {
        val imports = mutableSetOf<String>()
        val typeStr = buildTypeString(type, currentPackage, imports)
        return typeStr to imports
    }

    private fun buildTypeString(
        type: KSType,
        currentPackage: String,
        imports: MutableSet<String>
    ): String {
        val declaration = type.declaration
        val qualifiedName = declaration.qualifiedName?.asString()
            ?: declaration.simpleName.asString()
        val simpleName = declaration.simpleName.asString()

        // kotlin.* 自动导入；同包不需要 import
        val declarationPackage = declaration.packageName.asString()
        if (!qualifiedName.startsWith("kotlin.") && declarationPackage != currentPackage) {
            imports.add(qualifiedName)
        }

        val sb = StringBuilder(simpleName)

        if (type.arguments.isNotEmpty()) {
            sb.append("<")
            type.arguments.forEachIndexed { index, arg ->
                if (index > 0) sb.append(", ")
                when (arg.variance) {
                    Variance.STAR -> sb.append("*")
                    else -> {
                        val argType = arg.type?.resolve()
                        if (argType != null) {
                            sb.append(buildTypeString(argType, currentPackage, imports))
                        }
                    }
                }
            }
            sb.append(">")
        }

        if (type.isMarkedNullable) {
            sb.append("?")
        }

        return sb.toString()
    }

    private fun OutputStream.appendText(str: String) {
        write(str.toByteArray())
    }
}
