package com.example.archshowcase.replayable.processor

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.symbol.KSClassDeclaration
import java.io.OutputStream

/**
 * 为 @ReplayableStore 注解生成 Factory 辅助代码
 */
class StoreFactoryGenerator(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger
) {
    fun generate(
        packageName: String,
        storeName: String,
        storeClassName: String,
        stateClassName: String,
        recordClassName: String,
        classDeclaration: KSClassDeclaration
    ) {
        val fileName = "${storeName}FactoryHelpers"
        val file = codeGenerator.createNewFile(
            Dependencies(true, classDeclaration.containingFile!!),
            packageName,
            fileName
        )

        file.use { out ->
            out.appendText("// Auto-generated by Replayable KSP Processor\n")
            out.appendText("@file:Suppress(\"unused\")\n\n")
            out.appendText("package $packageName\n\n")
            out.appendText("import com.example.archshowcase.core.trace.restore.RestoreRegistry\n\n")

            // 生成 STORE_NAME 常量
            val storeNameConstant = toSnakeCase(storeName) + "_NAME"
            out.appendText("""
                |/** Store name constant for $storeName */
                |const val $storeNameConstant = "$storeName"
                |
            """.trimMargin())

            // 生成 resolveXxxInitialState() 辅助函数
            val functionName = "resolve${storeName}InitialState"
            out.appendText("""
                |/**
                | * Resolve initial state from RestoreRegistry or create default
                | *
                | * @return Pair of (initialState, needsBootstrap)
                | */
                |fun $functionName(): Pair<$storeClassName, Boolean> {
                |    val restored = RestoreRegistry.resolveInitialState<$storeClassName>($storeNameConstant)
                |    return if (restored != null) {
                |        restored to false
                |    } else {
                |        $storeClassName() to true
                |    }
                |}
                |
            """.trimMargin())
        }
    }

    private fun toSnakeCase(str: String): String {
        return str.replace(Regex("([a-z])([A-Z])"), "$1_$2").uppercase()
    }

    private fun OutputStream.appendText(str: String) {
        this.write(str.toByteArray())
    }
}
